'use strict';

/**
 * Build data/interaction-why.json: DDInter 2.0's own mechanism/management text for the pairs in
 * data/interaction-index.json that data/build/why-raw.json (git-ignored; a DDInter interaction page
 * per pair, fetched separately) also covers.
 *
 * Input: data/build/why-raw.json - { meta, pairs: { "<DDInterID>|<DDInterID>": { idA, nameA, idB,
 * nameB, level, files, interactionId, url, mechanism, management } } }. Every mechanism/management
 * string is DDInter's own prose, copied verbatim; nothing here rewrites, shortens or interprets it.
 * The one exception (stripTagWidget, below): DDInter's page also carries an adverse-event TAG
 * WIDGET next to the prose (a bare list of unrelated condition names ending in the word "More"),
 * and the scraper that produced why-raw.json copied the whole table cell including it. That tag
 * list was never DDInter's mechanism/management prose, so it is cut before anything else touches
 * the string - this is scraper-artifact removal, not paraphrasing.
 *
 * Translation: why-raw.json is keyed by DDInter ids; data/interaction-index.json is keyed by this
 * system's canonical drug names (src/normalise.js). Each why-raw pair's ids are mapped back to index
 * keys through index.drugs[k].ddinterId (the same field scripts/build-demo-index.js records), then
 * re-keyed with the index's own pairKey ordering. A why-raw pair whose drug(s) fell outside the
 * index's scope, or whose pair never got a row in the index, is left out (not this index's problem
 * to have an opinion about) - a pair present in the index but missing verbatim text is left out and
 * logged (never invented). The index's own recorded level is authoritative for the output; a
 * mismatch against why-raw's snapshot level is logged, never silently trusted either way.
 *
 * `summary` is always written null: an AI paraphrase of the mechanism/management text is a SEPARATE,
 * later step (never generated by this script), and every summary needs a doctor's confirmation
 * before it is relied on (D23/D27-style human-in-the-loop, same as every other agent-drafted clinical
 * value in this project) - `meta.summaries` says so on the file itself.
 *
 * DDInter 2.0 is CC BY-NC-SA 4.0 (https://ddinter.scbdd.com/) - meta carries that on every build,
 * same as data/interaction-index.json.
 *
 *   node scripts/build-why.js             write data/interaction-why.json
 *   node scripts/build-why.js --dry-run   print what would be written, write nothing
 */
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');

const ROOT = path.join(__dirname, '..');
const INDEX = path.join(ROOT, 'data', 'interaction-index.json');
const WHY_RAW = path.join(ROOT, 'data', 'build', 'why-raw.json');
const OUT = path.join(ROOT, 'data', 'interaction-why.json');
const LICENCE = 'CC BY-NC-SA 4.0';
const GRADED = { Major: 3, Moderate: 2, Minor: 1 };
const SUMMARIES_NOTE = 'AI draft written only from the DDInter text beside it; a doctor confirms it before relying on it';

/**
 * DDInter's own interaction page carries an "adverse event" tag widget (a flat list of unrelated
 * condition names ending in the literal word "More") beside the mechanism/management prose. The
 * scraper that produced why-raw.json copied the whole table cell, so some verbatim strings end
 * with this tag list glued on with no punctuation of its own - e.g. "...CYP450 3A4. abdominal
 * distension angina angioedema ... cerebral infarct More". None of that tag text is mechanism or
 * management prose, and showing it as such would present unrelated conditions as part of the
 * interaction's own text.
 *
 * A string with this widget always still ends its REAL prose with a sentence-ending period before
 * the tag list starts (checked against all 166 affected mechanism strings on 2026-09-26 - every
 * one has at least one period). So: only when the string ends in " More" literally, cut everything
 * after the LAST period and keep the period. A string that doesn't end in " More" is returned
 * unchanged - this never touches ordinary prose that happens to contain the word "more".
 */
function stripTagWidget(text) {
  if (!text || !/ More$/.test(text)) return { text, cut: null };
  const lastPeriod = text.lastIndexOf('.');
  if (lastPeriod === -1) return { text, cut: null };   // no sentence boundary to cut at - leave it, never guess
  return { text: text.slice(0, lastPeriod + 1).trim(), cut: text.slice(lastPeriod + 1).trim() };
}

function main() {
  const dry = process.argv.includes('--dry-run');
  if (!fs.existsSync(INDEX)) throw new Error('no data/interaction-index.json - run scripts/build-demo-index.js first');
  if (!fs.existsSync(WHY_RAW)) throw new Error('no data/build/why-raw.json - copy the fetched DDInter why-text in before running this');
  const index = JSON.parse(fs.readFileSync(INDEX, 'utf8'));
  const raw = JSON.parse(fs.readFileSync(WHY_RAW, 'utf8'));
  if (!raw.pairs || typeof raw.pairs !== 'object') throw new Error('data/build/why-raw.json has no pairs{}');

  // DDInterID -> this index's canonical key, from the very field build-demo-index.js records.
  const byDdinterId = new Map();
  for (const [key, d] of Object.entries(index.drugs)) if (d && d.ddinterId) byDdinterId.set(d.ddinterId, key);

  const outPairs = {};
  const droppedOutOfScope = [];
  const droppedNoIndexRow = [];
  const droppedMissingText = [];
  const droppedUngraded = [];
  const levelMismatches = [];
  const tagWidgetsCut = [];

  for (const [rawKey, p] of Object.entries(raw.pairs)) {
    const keyA = byDdinterId.get(p.idA);
    const keyB = byDdinterId.get(p.idB);
    if (!keyA || !keyB || keyA === keyB) { droppedOutOfScope.push(rawKey + ' (' + p.nameA + ' x ' + p.nameB + ')'); continue; }
    const pairKey = keyA < keyB ? keyA + '|' + keyB : keyB + '|' + keyA;
    const row = index.pairs[pairKey];
    if (!row) { droppedNoIndexRow.push(pairKey + ' (' + p.nameA + ' x ' + p.nameB + ')'); continue; }
    if (GRADED[row.level] === undefined) { droppedUngraded.push(pairKey + ': index level ' + row.level); continue; }
    const mechanismRaw = p.mechanism ? String(p.mechanism).trim() : '';
    const managementRaw = p.management ? String(p.management).trim() : '';
    if (!mechanismRaw || !managementRaw) { droppedMissingText.push(pairKey); continue; }
    const mechCut = stripTagWidget(mechanismRaw);
    const mgmtCut = stripTagWidget(managementRaw);
    const mechanism = mechCut.text;
    const management = mgmtCut.text;
    if (mechCut.cut) tagWidgetsCut.push(pairKey + ' (mechanism): ' + mechCut.cut);
    if (mgmtCut.cut) tagWidgetsCut.push(pairKey + ' (management): ' + mgmtCut.cut);
    if (row.level !== p.level) levelMismatches.push(pairKey + ': index=' + row.level + ', why-raw=' + p.level + ' (index kept)');
    const sourceSha256 = crypto.createHash('sha256').update(mechanism + '\n' + management).digest('hex');
    outPairs[pairKey] = { level: row.level, url: p.url, mechanism, management, summary: null, sourceSha256 };
  }

  const sortedPairs = Object.fromEntries(Object.entries(outPairs).sort(([x], [y]) => x.localeCompare(y)));
  const out = {
    meta: {
      source: 'DDInter 2.0',
      url: 'https://ddinter.scbdd.com/',
      licence: LICENCE,
      citation: index.meta.source.citation,
      retrievedAt: raw.meta.retrievedAt || index.meta.builtAt,
      summaries: SUMMARIES_NOTE
    },
    pairs: sortedPairs
  };

  const byLevel = { Major: 0, Moderate: 0, Minor: 0 };
  for (const p of Object.values(sortedPairs)) byLevel[p.level] += 1;

  console.log('why-raw pairs read: ' + Object.keys(raw.pairs).length);
  console.log('written: ' + Object.keys(sortedPairs).length + ' (Major ' + byLevel.Major + ', Moderate ' + byLevel.Moderate + ', Minor ' + byLevel.Minor + ')');
  console.log('dropped - drug(s) outside the index scope: ' + droppedOutOfScope.length);
  for (const d of droppedOutOfScope) console.log('  out of scope: ' + d);
  console.log('dropped - pair has no row in interaction-index.json: ' + droppedNoIndexRow.length);
  for (const d of droppedNoIndexRow) console.log('  no index row: ' + d);
  console.log('dropped - index level is not graded (Unknown): ' + droppedUngraded.length);
  for (const d of droppedUngraded) console.log('  ' + d);
  console.log('dropped - missing mechanism/management text: ' + droppedMissingText.length);
  for (const d of droppedMissingText) console.log('  missing text: ' + d);
  console.log('DDInter tag-widget list cut off the end of verbatim text: ' + tagWidgetsCut.length);
  for (const t of tagWidgetsCut) console.log('  cut: ' + t);
  if (levelMismatches.length) { console.log('level mismatches (why-raw vs index; index wins): ' + levelMismatches.length); for (const m of levelMismatches) console.log('  ' + m); }

  if (!dry) fs.writeFileSync(OUT, JSON.stringify(out, null, 2) + '\n');
  console.log(dry ? '(dry run - nothing written)' : 'wrote data/interaction-why.json');
}

main();
