/**
 * docs/design-system/tokens.json → styles/tokens.css  (D-001)
 * The token file is the single source of visual values. This emits:
 *  - one custom property per colour, spacing, radius and shadow token (--navy, --space-3, …),
 *  - --font-sans — the one variable bundle.css reads that neither file defines,
 *  - --type-<style>-size/line/weight/tracking for the eight type styles and a .type-<style> class each,
 *  - the structural constants the brand book states in prose (hit areas, focus ring, content cap).
 * `--check` exits non-zero when the committed CSS is stale.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';

type Token = { name: string; value: string; usage?: string };
type Style = { name: string; fontSize: string; lineHeight: string; fontWeight: number; letterSpacing?: string; usage?: string };
type Tokens = {
  name: string;
  color: { tokens: Token[] };
  type: { families: Record<string, string>; groups: { name: string; family: string; styles: Style[] }[] };
  spacing: { tokens: Token[] };
  radius: { tokens: Token[] };
  shadow?: { tokens: Token[] };
};

const SRC = resolve('docs/design-system/tokens.json');
const OUT = resolve('styles/tokens.css');

export function compile(tokens: Tokens): string {
  const lines: string[] = [];
  lines.push('/* GENERATED by scripts/build-tokens.ts from docs/design-system/tokens.json — do not edit.');
  lines.push('   Every visual value in the product resolves to one of these custom properties. */');
  lines.push(':root {');
  lines.push('  /* colour */');
  for (const t of tokens.color.tokens) lines.push(`  --${t.name}: ${t.value};`);
  lines.push('  /* type family — the one variable bundle.css reads that tokens.json does not name */');
  lines.push(`  --font-sans: ${tokens.type.families.sans};`);
  lines.push('  /* spacing */');
  for (const t of tokens.spacing.tokens) lines.push(`  --${t.name}: ${t.value};`);
  lines.push('  /* radius */');
  for (const t of tokens.radius.tokens) lines.push(`  --${t.name}: ${t.value};`);
  lines.push('  /* elevation */');
  for (const t of tokens.shadow?.tokens ?? []) lines.push(`  --${t.name}: ${t.value};`);
  lines.push('  /* type styles */');
  const styles = tokens.type.groups.flatMap((g) => g.styles);
  for (const s of styles) {
    lines.push(`  --type-${s.name}-size: ${s.fontSize};`);
    lines.push(`  --type-${s.name}-line: ${s.lineHeight};`);
    lines.push(`  --type-${s.name}-weight: ${s.fontWeight};`);
    if (s.letterSpacing) lines.push(`  --type-${s.name}-tracking: ${s.letterSpacing};`);
  }
  lines.push('  /* structural constants stated in the brand book (not tokens, but not free values either) */');
  lines.push('  --hit-area: 44px;          /* minimum touch target */');
  lines.push('  --hit-area-primary: 48px;  /* primary action */');
  lines.push('  --target-gap: 8px;         /* clear space between adjacent targets */');
  lines.push('  --line: 1px;               /* hairline / control outline */');
  lines.push('  --line-2: 2px;             /* emphasised outline (error, selected) */');
  lines.push('  --ring: 3px;               /* focus ring */');
  lines.push('  --ring-gap: 2px;           /* on-fill halo inside the ring */');
  lines.push('  --icon: 24px;              /* icon box, minimum legible size for this audience */');
  lines.push('  --icon-sm: 20px;');
  lines.push('  --content-max: 880px;      /* desktop content cap (navigation.md) */');
  lines.push('  --breakpoint-tablet: 834px;');
  lines.push('  --breakpoint-desktop: 1440px;');
  lines.push('  /* the structural names bundle.css uses internally, aliased so ported styles resolve */');
  lines.push('  --wsf-hit: var(--hit-area); --wsf-line: var(--line); --wsf-line-2: var(--line-2);');
  lines.push('  --wsf-ring: var(--ring); --wsf-ring-gap: var(--ring-gap); --wsf-ico: var(--icon); --wsf-ico-sm: var(--icon-sm);');
  lines.push('  --wsf-tablet: var(--breakpoint-tablet);');
  lines.push('}');
  lines.push('');
  lines.push('/* One class per type style. Arabic is never uppercased or letter-spaced: tracking applies to Latin only. */');
  for (const s of styles) {
    lines.push(`.type-${s.name} { font-size: var(--type-${s.name}-size); line-height: var(--type-${s.name}-line); font-weight: var(--type-${s.name}-weight); }`);
    if (s.letterSpacing) lines.push(`:lang(en) .type-${s.name} { letter-spacing: var(--type-${s.name}-tracking); }`);
  }
  lines.push('');
  lines.push('/* Icon primitive shared by every ported component (bundle.css .wsf-ico). */');
  lines.push('.wsf-ico { inline-size: var(--icon); block-size: var(--icon); flex: none; fill: none; stroke: currentColor; stroke-width: 2; stroke-linecap: round; stroke-linejoin: round; }');
  lines.push('.wsf-ico--sm { inline-size: var(--icon-sm); block-size: var(--icon-sm); }');
  lines.push('/* Mirrors only glyphs that encode direction. Never a capsule, clock, checkmark or numeral. */');
  lines.push('[dir="rtl"] .wsf-mirror { transform: scaleX(-1); }');
  return lines.join('\n') + '\n';
}

const tokens = JSON.parse(readFileSync(SRC, 'utf8')) as Tokens;
const css = compile(tokens);
if (process.argv.includes('--check')) {
  const current = existsSync(OUT) ? readFileSync(OUT, 'utf8') : '';
  if (current !== css) {
    console.error(`✗ styles/tokens.css is stale against docs/design-system/tokens.json — run npm run build:tokens`);
    process.exit(1);
  }
  console.log('✓ styles/tokens.css is in sync with docs/design-system/tokens.json');
} else {
  writeFileSync(OUT, css);
  console.log(`✓ wrote ${OUT} (${css.split('\n').length} lines)`);
}
